* The Vatican might be the false church!

- https://www.tomorrowsworld.org/magazines/2002/november-december/the-trap-of-ecumenism
- https://mullikine.github.io/posts/gospel-of-thomas/

The reason I say this is that the seem to:
- overvalue ritual over actions of the heart ([[https://mullikine.github.io/posts/a-model-of-morality/][images instead of reality]])
  - For example, they believe that the sacrament itself is Holy, and not the words of Jesus which change the heart
- Worship images, totems and effigees

Effigies, such as described in there:

- https://mullikine.github.io/posts/spaceship-headed-for-mars/

---

- http://github.com/mullikine/christianity/blob/master/Christ.org

- [[http://www.earlychristianwritings.com/thomas/gospelthomas105.html][Thomas 105]]

#+BEGIN_SRC text -n :async :results verbatim code
  (105) Jesus said: He who knows father and mother will be called the son of a harlot.
#+END_SRC

This could be about coming to know both the
Father and the Mother Mary, actually, as a
direct attack against the Vatican, which might
be a false church.

I think this is about coming to know the
Father, and coming to 'know' the spirit of the
World, which is that of simulating the images
of the Apostles.

People can follow either without 'knowing' either one.

+ [[http://gnosis.org/naghamm/bookt.html][Book of Thomas the Contender]] (Jude Thomas, missionary to India) :: To the fool, however, the good and bad are the same - indeed the wise man will be nourished by the truth and (Ps. 1:3) "will be like a tree growing by the meandering stream" - seeing that there are some who, although having wings, rush upon the visible things, things that are far from the truth.

When they put Mary inside the Temple at Jerusalem, that could be one of the abominations?

Is the Mother 'Mary', or is the Mother 'the
world', or is it both?

But how to 'know' the Mother, is it by a
similar Bridal Chamber-like ceremony?

But how? By some kind of spiritual ceremony, probably.

+ [[http://gnosis.org/naghamm/bookt.html][Book of Thomas the Contender]] (Jude Thomas, missionary to India) :: To the fool, however, the good and bad are the same - indeed the wise man will be nourished by the truth and (Ps. 1:3) "will be like a tree growing by the meandering stream" - seeing that there are some who, although having wings, rush upon the visible things, things that are far from the truth.

** You see
The Vatican has taken the 'image' 

orders of simulacra
    Baudrillard's orders of simulacra exist as
    follows:
    - The first order of simulacra focuses on
      counterfeits and false images.
    - The second order of simulacra is
      dominated by production of these false
      images.
    - The third order of simulacra rests on
      ultimate simulation.


*** The Jesus' flesh is the Veil in the Holy of Holies
A person must have boldness to enter the Holy of Hohlies!

#+BEGIN_SRC text -n :async :results verbatim code
  15 But the Holy Spirit also witnesses to us;
  for after He had said before, 16 k“This is
  the covenant that I will make with them
  after those days, says the Lord: I
  will put My laws into their hearts, and in
  their minds I will write them,” 17 then He
  adds, l“Their sins and their lawless deeds I
  will remember no more.” 18 Now where there is
  5remission of these, there is no longer an
  offering for sin.
#+END_SRC

---

Symbolically, I have personally entered the Holy of Holies, with boldness!

Bodacious means Bold and Audacious.

- [[https://mullikine.github.io/posts/thy-bridal-chamber/][Thy Bridal Chamber // Bodacious Blog]]

#+BEGIN_SRC text -n :async :results verbatim code
  19 Therefore, brethren, having mboldness 6to
  enter nthe Holiest by the blood of Jesus, 20
  by a new and oliving way which He consecrated
  for us, through the veil, that is, His flesh,
  21 and having a High Priest over the house of
  God, 22 let us pdraw near with a true heart
  qin full assurance of faith, having our hearts
  sprinkled from an evil conscience and our
  bodies washed with pure water. 23 Let us hold
  fast the confession of our hope without
  wavering, for rHe who promised is faithful. 24
  And let us consider one another in order to
  stir up love and good works, 25 snot forsaking
  the assembling of ourselves together, as is
  the manner of some, but exhorting one another,
  and tso much the more as you see uthe Day
  approaching.
#+END_SRC
